package dify

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"kairo/core"
	"kairo/ir"
)

// The differential harness (ADR 0028): Dify's workflow fixtures were run on
// graphon 0.7.0 with the external nodes mocked (harness/graphon_trace.py,
// regenerated by harness/gen_golden.sh into testdata/graphon). Here the
// same workflows are converted, run on kairo's core with the same mocks,
// and compared: the run's status and outputs, and every node that
// succeeded with its outputs.

type golden struct {
	Fixture  string                     `json:"fixture"`
	Inputs   map[string]json.RawMessage `json:"inputs"`
	Case     mockCase                   `json:"case"`
	Workflow json.RawMessage            `json:"workflow"`
	Status   string                     `json:"status"`
	Error    string                     `json:"error"`
	Outputs  map[string]any             `json:"outputs"`
	Trace    []struct {
		Event   string         `json:"event"`
		Node    string         `json:"node"`
		Outputs map[string]any `json:"outputs"`
	} `json:"trace"`
}

// mockCase overrides the mocks: outputs of nodes, or failures.
type mockCase struct {
	Outputs map[string]map[string]any `json:"outputs"`
	Errors  map[string]string         `json:"errors"`
	// Human decides human input nodes: an action and the submitted
	// outputs, or that the form expired. Default: the first action.
	Human map[string]struct {
		Handle  string         `json:"handle"`
		Outputs map[string]any `json:"outputs"`
		Expired bool           `json:"expired"`
	} `json:"human"`
}

// mockOutputs is harness/graphon_trace.py's default_outputs.
func mockOutputs(typ, id string, params json.RawMessage) map[string]any {
	switch typ {
	case "llm":
		return map[string]any{"text": "llm:" + id}
	case "template-transform":
		return map[string]any{"output": "tpl:" + id}
	case "http-request":
		return map[string]any{"status_code": 200, "body": "http:" + id, "headers": map[string]any{}, "files": []any{}}
	case "tool":
		return map[string]any{"text": "tool:" + id, "files": []any{}, "json": []any{}}
	case "question-classifier":
		var d struct {
			Classes []struct {
				ID string `json:"id"`
			} `json:"classes"`
		}
		json.Unmarshal(params, &d)
		first := ""
		if len(d.Classes) > 0 {
			first = d.Classes[0].ID
		}
		return map[string]any{"class_id": first, "class_name": "qc:" + id}
	case "parameter-extractor":
		return map[string]any{"__is_success": 1, "__reason": nil}
	case "code":
		var d struct {
			Outputs map[string]struct {
				Type string `json:"type"`
			} `json:"outputs"`
		}
		json.Unmarshal(params, &d)
		out := map[string]any{}
		for name, o := range d.Outputs {
			switch o.Type {
			case "number":
				out[name] = 1
			case "boolean":
				out[name] = true
			case "object":
				out[name] = map[string]any{"node": id}
			case "array[string]":
				out[name] = []any{"code:" + id}
			case "array[number]":
				out[name] = []any{1}
			case "array[object]":
				out[name] = []any{map[string]any{"node": id}}
			case "array[boolean]":
				out[name] = []any{true}
			default:
				out[name] = "code:" + id
			}
		}
		return out
	}
	return map[string]any{}
}

// run drives the core until the run is done, answering dispatches with the
// mocks and firing timers in order.
func run(t *testing.T, p *ir.Plan, input json.RawMessage, mc mockCase) (*core.State, []core.Trace) {
	t.Helper()
	s := core.NewState("run")
	var traces []core.Trace
	var pending []core.Command
	timers := map[uint32]core.Command{}
	now := int64(1000)
	apply := func(ev core.Event) {
		ev.At = now
		out, tr, err := core.ApplyTraced(p, s, &ev, nil, traces)
		traces = tr
		if err != nil && err != core.ErrIgnored {
			t.Fatal(err)
		}
		for _, c := range out {
			switch c.Kind {
			case core.CmdDispatch:
				pending = append(pending, c)
			case core.CmdTimer:
				timers[c.Timer] = c
			case core.CmdCancelTimer:
				delete(timers, c.Timer)
			case core.CmdAbort:
				pending = slices.DeleteFunc(pending, func(x core.Command) bool { return x.Act == c.Act })
			}
		}
	}
	apply(core.Event{Kind: core.EvStart, Data: input})
	for steps := 0; !s.Status.Done() && steps < 100000; steps++ {
		if len(pending) > 0 {
			c := pending[0]
			pending = pending[1:]
			n := &p.Nodes[c.Node]
			typ := strings.TrimPrefix(n.Spec.Action, "dify.")
			if msg, ok := mc.Errors[n.ID]; ok {
				apply(core.Event{Kind: core.EvStepErr, Act: c.Act, Attempt: c.Attempt, Err: msg, ErrType: "MockError", Retryable: true})
				continue
			}
			out := mockOutputs(typ, n.ID, n.Params)
			if o, ok := mc.Outputs[n.ID]; ok {
				out = o
			}
			if _, ok := out[n.Spec.Branch]; len(n.Handles) > 0 && !ok {
				out[n.Spec.Branch] = n.Handles[0]
			}
			b, _ := json.Marshal(out)
			apply(core.Event{Kind: core.EvStepOK, Act: c.Act, Attempt: c.Attempt, Data: b})
			continue
		}
		// A person answers the human input nodes that wait.
		if waits := core.Waits(p, s); len(waits) > 0 {
			w := waits[0]
			id := strings.TrimPrefix(w.Signal, "human-input:")
			d, ok := mc.Human[id]
			if !ok {
				// The first action: the route's first case after the timeout.
				if r, ok := p.ByID[id+"__route"]; ok && len(p.Nodes[r].Switch.Cases) > 1 {
					d.Handle = p.Nodes[r].Switch.Cases[1].ID
				}
			}
			if d.Expired {
				for _, c := range timers {
					if c.Act == w.Act {
						delete(timers, c.Timer)
						now = max(now, c.At)
						apply(core.Event{Kind: core.EvTimer, Act: c.Act, Timer: c.Timer})
						break
					}
				}
				continue
			}
			payload, _ := json.Marshal(map[string]any{"handle": d.Handle, "outputs": d.Outputs})
			apply(core.Event{Kind: core.EvSignal, Act: w.Act, Name: w.Signal, Data: payload})
			continue
		}
		if len(timers) == 0 {
			break
		}
		var first core.Command
		for _, c := range timers {
			if first.Timer == 0 || c.At < first.At || c.At == first.At && c.Timer < first.Timer {
				first = c
			}
		}
		delete(timers, first.Timer)
		now = max(now, first.At)
		apply(core.Event{Kind: core.EvTimer, Act: first.Act, Timer: first.Timer})
	}
	return s, traces
}

// canonical renders v as sorted JSON for comparison: numbers by value, so
// graphon's 1 and kairo's 1.0 agree where JSON cannot tell them apart.
func canonical(v any) string {
	b, _ := json.Marshal(v)
	var x any
	d := json.NewDecoder(bytes.NewReader(b))
	d.UseNumber()
	d.Decode(&x)
	var norm func(any) any
	norm = func(v any) any {
		switch y := v.(type) {
		case json.Number:
			f, _ := y.Float64()
			return f
		case []any:
			for i := range y {
				y[i] = norm(y[i])
			}
		case map[string]any:
			for k := range y {
				y[k] = norm(y[k])
			}
		}
		return v
	}
	out, _ := json.Marshal(norm(x))
	return string(out)
}

func TestGraphonParity(t *testing.T) {
	files, _ := filepath.Glob("testdata/graphon/*.json")
	if len(files) == 0 {
		t.Fatal("no golden files; run harness/gen_golden.sh")
	}
	for _, f := range files {
		t.Run(strings.TrimSuffix(filepath.Base(f), ".json"), func(t *testing.T) {
			var g golden
			data, err := os.ReadFile(f)
			if err != nil {
				t.Fatal(err)
			}
			if err := json.Unmarshal(data, &g); err != nil {
				t.Fatal(err)
			}
			var w Workflow
			if err := json.Unmarshal(g.Workflow, &w); err != nil {
				t.Fatal(err)
			}
			conv, err := Convert(g.Fixture, &w)
			if err != nil {
				t.Fatalf("convert: %v", err)
			}
			reg := ir.NewRegistry()
			for _, s := range conv.Specs {
				reg.Register(s)
			}
			p, err := ir.Compile(conv.Definition, reg)
			if err != nil {
				def, _ := json.MarshalIndent(conv.Definition, "", " ")
				t.Fatalf("compile: %v\n%s", err, def)
			}
			in := map[string]json.RawMessage{}
			for k, v := range g.Inputs {
				in[k] = v
			}
			sys := map[string]any{"files": []any{}}
			if q, ok := g.Inputs["query"]; ok {
				sys["query"] = q
			}
			in["sys"], _ = json.Marshal(sys)
			in[EnvInput], _ = json.Marshal(EnvValues(&w))
			input, _ := json.Marshal(in)
			s, traces := run(t, p, input, g.Case)

			// Status.
			status := "succeeded"
			if s.Status != core.StatusCompleted {
				status = "failed"
			}
			if status != g.Status {
				t.Fatalf("status %s (%s), graphon %s (%s)", status, s.Error, g.Status, g.Error)
			}
			// Nodes that succeeded, with their outputs.
			skip := func(id string) bool {
				switch w.nodeType(id) {
				case "start", "iteration-start", "loop-start":
					return true
				}
				return strings.HasSuffix(id, "__route") // a human input's branch
			}
			var want, got []string
			for _, ev := range g.Trace {
				if (ev.Event == "NodeRunSucceededEvent" || ev.Event == "NodeRunExceptionEvent") && !skip(ev.Node) {
					want = append(want, ev.Node+" "+canonical(normalize(ev.Outputs)))
				}
			}
			outputs := map[string]any{}
			for _, tr := range traces {
				if tr.Kind != core.TrNodeEnd || tr.Status == "failed" {
					continue
				}
				id := p.Nodes[tr.Node].ID
				if skip(id) || strings.HasPrefix(id, "__") {
					continue
				}
				var out any
				json.Unmarshal(tr.Output, &out)
				switch w.nodeType(id) {
				case "iteration":
					out = map[string]any{"output": out}
				case "human-input":
					// The node's outputs are the submitted form.
					var sig struct {
						Payload struct {
							Outputs map[string]any `json:"outputs"`
						} `json:"payload"`
					}
					json.Unmarshal(tr.Output, &sig)
					out = map[string]any{}
					for k, v := range sig.Payload.Outputs {
						out.(map[string]any)[k] = v
					}
				}
				m, _ := out.(map[string]any)
				got = append(got, id+" "+canonical(normalize(m)))
				if slices.Contains(conv.Responses, id) {
					for k, v := range m {
						if k == "answer" {
							prev, _ := outputs["answer"].(string)
							v = prev + fmt.Sprint(v)
						}
						outputs[k] = v
					}
				}
			}
			slices.Sort(want)
			slices.Sort(got)
			// In a failed run, how far parallel branches got before the
			// failure stopped them depends on scheduling (graphon runs them
			// on threads): only the status is compared.
			if status == "succeeded" && !slices.Equal(want, got) {
				t.Errorf("succeeded nodes differ:\n graphon: %s\n kairo:   %s", strings.Join(want, "\n          "), strings.Join(got, "\n          "))
			}
			// The run's outputs.
			if a, b := canonical(normalize(g.Outputs)), canonical(normalize(outputs)); status == "succeeded" && a != b {
				t.Errorf("outputs differ:\n graphon: %s\n kairo:   %s", a, b)
			}
		})
	}
}

// normalize drops what the comparison cannot see the same way on both
// sides: answer files (graphon's file segments, empty here).
func normalize(m map[string]any) map[string]any {
	out := map[string]any{}
	for k, v := range m {
		if k == "files" {
			if l, ok := v.([]any); ok && len(l) == 0 {
				continue
			}
			if v == nil {
				continue
			}
		}
		out[k] = v
	}
	return out
}

func (w *Workflow) nodeType(id string) string {
	for _, n := range w.Graph.Nodes {
		if n.ID == id {
			var c common
			json.Unmarshal(n.Data, &c)
			return c.Type
		}
	}
	return ""
}
